# before "kubectl apply -f <instance>.yaml", do it:
# > kubectl apply -f spark-master.yaml
# > kubectl expose deployment spark-master --type=NodePort --target-port=8080 --name=spark-master-ui

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:3.5.1
        environment:
          - SPARK_MODE=master
        # - SPARK_NO_DAEMONIZE: true
        # - SPARK_RPC_AUTHENTICATION_ENABLED: no
        # - SPARK_RPC_AUTHENTICATION_SECRET: nil
        # - SPARK_RPC_ENCRYPTION_ENABLED: no
        # - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
        # - SPARK_SSL_ENABLED: no
        # - SPARK_SSL_KEY_PASSWORD: nil
        # - SPARK_SSL_KEYSTORE_PASSWORD: nil
        # - SPARK_SSL_KEYSTORE_FILE: ${SPARK_CONF_DIR}/certs/spark-keystore.jks
        # - SPARK_SSL_TRUSTSTORE_PASSWORD: nil
        # - SPARK_SSL_TRUSTSTORE_FILE: ${SPARK_CONF_DIR}/certs/spark-truststore.jks
        # - SPARK_SSL_NEED_CLIENT_AUTH: yes
        # - SPARK_SSL_PROTOCOL: TLSv1.2
        # - SPARK_WEBUI_SSL_PORT: nil
        # - SPARK_METRICS_ENABLED: false
        ports:
        - containerPort: 7077
        - containerPort: 8080