networks:
  kong-net:
    driver: bridge

volumes:
  es_data:
  kongdb:
  ls_data:
  kb_data:

services:

  kongdb:
    image: postgres:16-alpine
    container_name: kong-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "kong-admin"
      POSTGRES_PASSWORD: "kong*54321"
      POSTGRES_DB: "kongdb"
    networks:
      - kong-net
    ports:
      - "5432:5432"
    volumes:
      - ./kongdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong-admin"]
      interval: 30s
      timeout: 30s
      retries: 3
  
  redis:
    image: redis:7.2.5-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 30s
      retries: 50
      start_period: 30s
  
  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - kong-net
    volumes:
      - ./es_data:/usr/share/elasticsearch/data/
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - network.host=localhost

  logstash:
    image: logstash:8.13.4
    container_name: logstash
    restart: unless-stopped
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./ls_data:/usr/share/logstash/data
    networks:
      - kong-net
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.13.4
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kb_data:/usr/share/kibana/data
    networks:
      - kong-net
    depends_on:
      - elasticsearch

  kong-api-gateway:
    image: kong:3.6.1
    container_name: kong-gateway
    restart: unless-stopped
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: "kong-db"
      KONG_PG_PORT: 5432
      KONG_PG_USER: "kong-admin"
      KONG_PG_PASSWORD: "kong*54321"
      KONG_PG_DATABASE: "kongdb"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kongdb
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "kong-api-gateway", "health"]
      interval: 10s
      timeout: 10s
      retries: 10