# Client driver must be a PySpark 3.5.1 with Python 3.11.9.
# >> docker compose up --scale spark-worker=3

networks:
  spark-network:
    driver: bridge

services:
  
  spark-master:
    image: bitnami/spark:3.5.1
    hostname: spark-master
    container_name: bitnami-spark-master
    environment:
      - SPARK_MODE=master
      # - SPARK_MASTER_URL=spark://spark-master:7077
      # - SPARK_NO_DAEMONIZE=true
      # - SPARK_RPC_AUTHENTICATION_ENABLED=no
      # - SPARK_RPC_AUTHENTICATION_SECRET=nil
      # - SPARK_RPC_ENCRYPTION_ENABLED=no
      # - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      # - SPARK_SSL_ENABLED=no
      # - SPARK_SSL_KEY_PASSWORD=nil
      # - SPARK_SSL_KEYSTORE_PASSWORD=nil
      # - SPARK_SSL_KEYSTORE_FILE=${SPARK_CONF_DIR}/certs/spark-keystore.jks
      # - SPARK_SSL_TRUSTSTORE_PASSWORD=nil
      # - SPARK_SSL_TRUSTSTORE_FILE=${SPARK_CONF_DIR}/certs/spark-truststore.jks
      # - SPARK_SSL_NEED_CLIENT_AUTH=yes
      # - SPARK_SSL_PROTOCOL=TLSv1.2
      # - SPARK_WEBUI_SSL_PORT=nil
      # - SPARK_METRICS_ENABLED=false
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1024mb
      # - SPARK_NO_DAEMONIZE=true
      # - SPARK_RPC_AUTHENTICATION_ENABLED=no
      # - SPARK_RPC_AUTHENTICATION_SECRET=nil
      # - SPARK_RPC_ENCRYPTION_ENABLED=no
      # - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      # - SPARK_SSL_ENABLED=no
      # - SPARK_SSL_KEY_PASSWORD=nil
      # - SPARK_SSL_KEYSTORE_PASSWORD=nil
      # - SPARK_SSL_KEYSTORE_FILE=${SPARK_CONF_DIR}/certs/spark-keystore.jks
      # - SPARK_SSL_TRUSTSTORE_PASSWORD=nil
      # - SPARK_SSL_TRUSTSTORE_FILE=${SPARK_CONF_DIR}/certs/spark-truststore.jks
      # - SPARK_SSL_NEED_CLIENT_AUTH=yes
      # - SPARK_SSL_PROTOCOL=TLSv1.2
      # - SPARK_WEBUI_SSL_PORT=nil
      # - SPARK_METRICS_ENABLED=false
    networks:
      - spark-network