version: "3"

networks:
  microsoft-sql-server:

volumes:
  mssql-data:
  mssql-log:
  mssql-secrets:

services:
  microsoft-sql-server: # link: https://hub.docker.com/_/microsoft-mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: microsoft-sql-server
    environment:
      MSSQL_SA_USER: "sa"
      MSSQL_SA_PASSWORD: "mssql*54321"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - microsoft-sql-server
    volumes:
      - $PWD/mssql-data:/var/opt/mssql/data
      - $PWD/mssql-log:/var/opt/mssql/log
      - $PWD/mssql-secrets:/var/opt/mssql/secrets