version: "3"

volumes:
  shared-workspace:
    name: "distributed-file-system"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./

services:
  jupyterlab:
    image: jupyterlab:latest
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./shared-workspace:/opt/workspace
  
  hudi-master:
    image: hudi-master:latest
    container_name: hudi-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./shared-workspace:/opt/workspace
  
  hudi-worker-1:
    image: hudi-worker:latest
    container_name: hudi-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - hudi-master
  
  hudi-worker-2:
    image: hudi-worker:latest
    container_name: hudi-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - hudi-master