version: "3"

networks:
  kong-net:
    driver: bridge

volumes:
  postgresql:

services:
  
  kong-db:
    image: postgres:13-alpine
    container_name: kong-db
    restart: on-failure
    environment:
      POSTGRES_USER: "kong-admin"
      POSTGRES_PASSWORD: "kong*54321"
      POSTGRES_DB: "kongdb"
    networks:
      - kong-net
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong-admin"]
      interval: 30s
      timeout: 30s
      retries: 3

  kong-api-gateway:
    image: kong:3.6.1
    container_name: kong-gateway
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: "kong-db"
      KONG_PG_USER: "kong-admin"
      KONG_PG_PASSWORD: "kong*54321"
      KONG_PG_DATABASE: "kongdb"
      # KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      # KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      # KONG_PROXY_ERROR_LOG: "/dev/stderr"
      # KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-db
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "kong-api-gateway", "health"]
      interval: 10s
      timeout: 10s
      retries: 10