# Client driver must be a PySpark 3.5.1 with Python 3.8.10
# >> docker compose up --scale spark-worker=3

networks:
  spark-network:
    driver: bridge

services:

  spark-master:
    image: spark:python3
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip spark-master --port 7077 --webui-port 8080

  spark-worker:
    image: spark:python3
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1024m
    depends_on:
      - spark-master
    networks:
      - spark-network
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077