version: '3'

networks:
  influxdb:

volumes:
  influxdb:

services:
  influxdb: # https://hub.docker.com/_/influxdb
    image: influxdb:2.7.6
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb-admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxdb*54321
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token-1234567890!@#$%¨&*()
      - V1_DB_NAME=v1-db
      - V1_RP_NAME=v1-rp
      - V1_AUTH_USERNAME=v1-user
      - V1_AUTH_PASSWORD=v1-password
    ports:
      - 8086:8086
    networks:
      - influxdb
    volumes:
      - "$PWD/data:/var/lib/influxdb2"
      - "$PWD/config:/etc/influxdb2"
      - "$PWD/scripts:/docker-entrypoint-initdb.d"