version: '3'

volumes:
  postgresql:

services:

  postgresql: # https://hub.docker.com/_/postgres
    image: postgres:16.3-alpine
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_USER: postgres-admin
      POSTGRES_PASSWORD: postgres*54321
      POSTGRES_DB: postgresdb
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_HOST_AUTH_METHOD: "--auth-host=scram-sha-256"
      # POSTGRES_INITDB_WALDIR: "--locale-provider=icu --icu-locale=de-DE"
      # PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      # - ./my-postgres.conf":/etc/postgresql/postgresql.conf
    # volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres-admin"]
      interval: 30s
      timeout: 30s
      retries: 3

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8080:8080