services:

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    ports:
      - "9001:9000"
      - "9002:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-54321
    command: server /data --console-address ":9001"

  hadoop:
    image: apache/hadoop:3.3.6
    volumes:
      - ./hadoop-data:/hadoop
    environment:
      CORE_CONF_fs_defaultFS: hdfs://hadoop:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    command: bash -c "hdfs namenode -fm && mapred --daemon start historyserver"

  metastore-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: hive-admin
      POSTGRES_PASSWORD: hive*54321
      POSTGRES_DB: metastore-db
    volumes:
      - ./metastore-db:/var/lib/postgresql/data
  
  hive-metastore:
    image: apache/hive:4.0.0
    volumes:
      - ./hive-data:/hive
    environment:
      HIVE_SITE_CONF_hive_server2_authentication: NONE
      HIVE_SITE_CONF_datanucleus_autoCreateSchema: "true"
      HIVE_SITE_CONF_hive_metastore_uris: "thrift://127.0.0.1:9083"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: "jdbc:derby:;databaseName=/hive/metastore-db;create=true"
    depends_on:
      - metastore-db
    ports:
      - "9083:9083"
    command: hive --service metastore

  hudi:
    container_name: hudi
    image: hudi:latest
    # build: ./apache-hudi.dockerfile
    depends_on:
      - hadoop
      # - hive-metastore
    volumes:
      - ./hudi-data:/hudi
    environment:
      HADOOP_CONF_DIR: "/hadoop/etc/hadoop"
      HUDI_CONF_BASE_PATH: "hdfs://hadoop:9000/hudi"
      HUDI_CONF_HIVE_SYNC_ENABLED: "true"
      HUDI_CONF_HIVE_METASTORE_URI: "thrift://hive-metastore:9083"
    ports:
      - "8081:8081"
    command: bash -c "spark-submit --master local[2] --class org.apache.hudi.utilities.sources.helpers.IngestionCommitObserver /hudi/packaging/hudi-utilities-bundle/target/hudi-utilities-bundle_0.12.1.jar"

  airflow:
    image: apache/airflow:2.5.1
    volumes:
      - ./airflow-data:/opt/airflow
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      - postgres
    command: webserver

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  superset:
    image: apache/superset:2.0.1
    volumes:
      - ./superset-data:/var/lib/superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_WEBSERVER_ADDRESS: "0.0.0.0:8088"
      SUPERSET_WEBSERVER_PORT: 8088
      SUPERSET_METADATA_DB_URI: postgresql+psycopg2://superset:superset@postgres/superset
    depends_on:
      - postgres

  amundsen:
    image: amundsenmetadata/amundsen:4.2.2
    volumes:
      - ./amundsen-data:/app/amundsen/metadata/data
    ports:
      - "8081:8081"
    environment:
      AMUNDSEN_AUTH_PROVIDER: "no_auth"
      AMUNDSEN_METADATA_PROXY_USER: "minio"
      AMUNDSEN_METADATA_PROXY_PASSWORD: "minio123"
      AMUNDSEN_METADATA_PROXY_HOST: minio
      AMUNDSEN_METADATA_PROXY_PORT: 9000
      AMUNDSEN_METADATA_PROXY_PATH: "amundsen-data"
      AMUNDSEN_SEARCH_PROXY_ENABLED: "false"

  atlas:
    image: apache/atlas:2.2.0
    volumes:
      - ./atlas-data:/opt/atlas/data
    ports:
      - "21000:21000"
    environment:
      ATLAS_SERVER_OPTS: "-Xms512m -Xmx1024m"
      ATLAS_HDFS_FS_DEFAULT_FS: "hdfs://hadoop:9000"
      ATLAS_HDFS_FS_PROPERTIES: "hadoop.security.authentication=simple"
      ATLAS_HBASE_ZOOKEEPER_QUORUM: "hadoop"
      ATLAS_HBASE_ZOOKEEPER_PROPERTY_CLIENTPORT: "2181"
      ATLAS_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      - kafka
      - hadoop

  kafka:
    image: confluentinc/cp-kafka:6.1.9
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.9
    volumes:
      - ./zookeeper-data:/var/lib/zookeeper/data
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181