version: '3'

networks:
  elk:
    driver: bridge

volumes:
  es_data:
  ls_data:
  kb_data:

services:
  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    volumes:
      - ./es_data:/usr/share/elasticsearch/data/
      # - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - network.host=localhost

  logstash:
    image: logstash:8.13.4
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./ls_data:/usr/share/logstash/data
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kb_data:/usr/share/kibana/data
    networks:
      - elk
    depends_on:
      - elasticsearch